site_name: Wayne Ng Wei‑Yann — Portfolio
site_description: "Data / Cloud / Software portfolio — projects, experience, and contact."
site_url: https://example.com
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: indigo
      accent: blue

use_directory_urls: false
nav:
  - Home: index.md
  - About: about.md
  - Certifications: certifications.md
  - Projects: projects.md
  - Experience: experience.md
  - Skills: skills.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wayneng1998 (update)
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wayne-ng (update)
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.highlight
