name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs + Material
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --strict

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS CLI
        run: aws --version

      - name: Sync to S3
        run: aws s3 sync site/ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront (optional)
        if: ${{ env.CLOUDFRONT_DISTRIBUTION_ID && env.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
